
#pragma once

// Typehud configuration
#define TYPEHUD_FILLGRAPH
#define TYPEHUD_MATRIX_COLS 6
#define TYPEHUD_MATRIX_COL_SHIFT 0
// #define TYPEHUD_MATRIX_ROTATE_90
// #define TYPEHUD_MATRIX_ROTATE_180
// #define TYPEHUD_MATRIX_ROTATE_270

#define VIAL_KEYBOARD_UID {0x5C, 0x69, 0xA0, 0x59, 0xD3, 0x0D, 0xCF, 0x09}

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_UNLOCK_COMBO_ROWS { 0, 7 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 4 }
#define VIAL_ENCODER_DEFAULT { KC_VOLD, KC_VOLU, KC_MPRV, KC_MNXT, KC_TRNS, KC_TRNS }
