M48
; DRILL file {KiCad (6.0.0-0)} date 2022 April 10, Sunday 14:44:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-10T14:44:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
%
G90
G05
T1
X74.013Y-85.95
X109.825Y-124.15
X226.812Y-85.95
X231.587Y-124.15
T0
M30
